version: 2
# used to release in GITHUB
env_files:
  github_token: ~/.goreleaser/gh_token
  # needs repo scope

before:
  hooks:
    - go mod tidy
    - go mod vendor


builds:
  # =====================================================================================
  # Legacy AMD64 (Broad compatibility - GOAMD64 v1)
  # =====================================================================================
  - id: linux-amd64-legacy
    goos: [linux]
    goarch: [amd64]
    goamd64: [v1]
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/AndresBott/goback/app/metainfo.Version={{.Version}}
      - -X github.com/AndresBott/goback/app/metainfo.BuildTime={{.Date}}
      - -X github.com/AndresBott/goback/app/metainfo.ShaVer={{.Commit}}
    binary: goback

  # =====================================================================================
  # Modern AMD64 (Optimized for newer CPUs - GOAMD64 v3)
  # =====================================================================================
  - id: linux-amd64-modern
    goos: [linux]
    goarch: [amd64]
    goamd64: [v3]
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/AndresBott/goback/app/metainfo.Version={{.Version}}
      - -X github.com/AndresBott/goback/app/metainfo.BuildTime={{.Date}}
      - -X github.com/AndresBott/goback/app/metainfo.ShaVer={{.Commit}}
    binary: goback

  # =====================================================================================
  # ARM64 (Modern ARM targets like Raspberry Pi 4, ARM servers)
  # =====================================================================================
  - id: linux-arm64
    goos: [linux]
    goarch: [arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/AndresBott/goback/app/metainfo.Version={{.Version}}
      - -X github.com/AndresBott/goback/app/metainfo.BuildTime={{.Date}}
      - -X github.com/AndresBott/goback/app/metainfo.ShaVer={{.Commit}}
    binary: goback
    env:
      - CC=aarch64-linux-gnu-gcc

  # =====================================================================================
  # MacOs builds:
  # =====================================================================================
  - id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/AndresBott/goback/app/metainfo.Version={{.Version}}
      - -X github.com/AndresBott/goback/app/metainfo.BuildTime={{.Date}}
      - -X github.com/AndresBott/goback/app/metainfo.ShaVer={{.Commit}}
    flags:
      - -trimpath
    binary: goback
        

archives:
  - format: zip
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      goback
      {{- title .Os  }}_
      {{- if eq .Arch "amd64" }}x86_64_{{ .Amd64 }}
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}


# see full detail: https://goreleaser.com/customization/nfpm/
nfpms:
  - id: goback
    builds:
      - linux-amd64-legacy
      - linux-arm64
    package_name: goback
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.deb"

    maintainer: "Andres Bott <contact@andresbott.com>"
    description: |
      simple backup tool
    license: MIT
    formats:
      - deb

    #pacakge classification
    section: default
    priority: optional
    recommends:
      - cron
      - anacron

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    contents:
      - src: zarf/placeholder
        dst: /etc/goback/backupd.weekly/.placeholder
      - src: zarf/placeholder
        dst: /etc/goback/backupd.monthly/.placeholder
      - src: zarf/placeholder
        dst: /etc/goback/profiles/.placeholder
      - src: zarf/cron_weekly.sh
        dst: /etc/cron.weekly/run-goback
        file_info:
          mode: 0755
      - src: zarf/cron_monthly.sh
        dst: /etc/cron.monthly/run-goback
        file_info:
          mode: 0755

  - id: goback_modern
    builds: [linux-amd64-modern]
    package_name: goback
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_modern_cpu_v3.deb"

    maintainer: "Andres Bott <contact@andresbott.com>"
    description: |
      simple backup tool
    license: MIT
    formats:
      - deb

    #pacakge classification
    section: default
    priority: optional
    recommends:
      - cron
      - anacron

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    contents:
      - src: zarf/placeholder
        dst: /etc/goback/backupd.weekly/.placeholder
      - src: zarf/placeholder
        dst: /etc/goback/backupd.monthly/.placeholder
      - src: zarf/placeholder
        dst: /etc/goback/profiles/.placeholder
      - src: zarf/cron_weekly.sh
        dst: /etc/cron.weekly/run-goback
        file_info:
          mode: 0755
      - src: zarf/cron_monthly.sh
        dst: /etc/cron.monthly/run-goback
        file_info:
          mode: 0755


checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
