# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# used to release in GITHUB
env_files:
  github_token: ~/.goreleaser/gh_token

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux

    ldflags:
      - -s -w -X github.com/AndresBott/goback/app/cmd.Version={{.Version}}
      - -s -w -X github.com/AndresBott/goback/app/cmd.BuildTime={{.Date}}
      - -s -w -X github.com/AndresBott/goback/app/cmd.ShaVer={{.Commit}}

archives:
  - replacements:
      linux: Linux

# see full detail: https://goreleaser.com/customization/nfpm/
nfpms:
  -
    id: goback
    package_name: goback

    maintainer: "Andres Bott <contact@andresbott.com>"
    description: |
      simple backup tool
    license: MIT
    formats:
      - deb

    # Version Prerelease.
    # Default is extracted from `version` if it is semver compatible.
#    prerelease: snapshot

    #pacakge classification
    section: default
    priority: optional
    recommends:
      - cron
      - anacron

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    contents:
      - src: zarf/placeholder
        dst: /etc/goback/backupd.weekly/.placeholder
      - src: zarf/placeholder
        dst: /etc/goback/backupd.monthly/.placeholder
      - src: zarf/placeholder
        dst: /etc/goback/profiles/.placeholder
      - src: zarf/cron.sh
        dst: /etc/cron.weekly/goback.sh
      - src: zarf/cron.sh
        dst: /etc/cron.monthly/goback.sh

    # Scripts to execute during the installation of the package.
    # Keys are the possible targets during the installation process
    # Values are the paths to the scripts which will be executed
    scripts:
#      preinstall: "scripts/preinstall.sh"
      postinstall: "zarf/postinstall.sh"
#      preremove: "scripts/preremove.sh"
#      postremove: "scripts/postremove.sh"


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
