# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# used to release in GITHUB
env_files:
  github_token: ~/.goreleaser/gh_token

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux

    ldflags:
      - -s -w -X github.com/AndresBott/goback/app/cmd.Version={{.Version}}
      - -s -w -X github.com/AndresBott/goback/app/cmd.BuildTime={{.Date}}
      - -s -w -X github.com/AndresBott/goback/app/cmd.ShaVer={{.Commit}}

archives:
  - replacements:
      linux: Linux
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
